version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            APP_DEBUG: true
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: carservice
            DB_USERNAME: root
            DB_PASSWORD: root_password
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: carservice
        volumes:
            - db_data:/var/lib/mysql

    nginx:
        image: nginx:alpine
        container_name: nginx_server
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
    db_data:
